name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: install deps
      run: make deps

    - name: build
      run: make ba

    - name: run
      run: make run

    - name: unittest
      run: make unittest
